# Generated by Django 3.2.5 on 2021-07-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image2',
        ),
    ]
